config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  resources :types
  resources :teams, except:[:edit]
  post 'teams/:id/edit', to: 'teams#edit', as: 'edit_team'
  post 'teams/:id/admin', to: 'teams#admin', as: 'admin_team'
  resources :recruits, except:[:edit]
  post 'recruits/:id/edit', to: 'recruits#edit', as: 'edit_recruit'
  get 'about', to: 'about#index', as: 'about'
  resources :questionnaires
  get 'questionnaires/:id/answer', to: 'questionnaires#answer', as: 'answer_questionnaire'
  post 'questionnaires/:id/create_answer', to: 'questionnaires#create_answer', as: 'create_answer_questionnaire'
  get 'questionnaires/:id/index_answer', to: 'questionnaires#index_answer', as: 'index_answer_questionnaire'
  post 'questionnaires/:id/admin', to: 'questionnaires#admin', as: 'admin_questionnaire'
  get 'questionnaire_answers/:id', to: 'questionnaire_answers#show', as: 'questionnaire_answer'
  get 'questionnaire_items/:id', to: 'questionnaire_items#show', as: 'questionnaire_item'

end

app/models/questionnaire.rb
# == Schema Information
#
# Table name: questionnaires
#
#  id                 :integer          not null, primary key
#  access_token       :string           not null
#  title              :string           not null
#  header_discription :text
#  footer_discription :text
#  password_digest    :string           not null
#  published_from     :datetime         not null
#  published_to       :datetime         not null
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#

class Questionnaire < ApplicationRecord
  include FriendlyId
  friendly_id :access_token

  # SecurePassword有効
  has_secure_password
  has_many :questionnaire_items

  accepts_nested_attributes_for :questionnaire_items, allow_destroy: true


  before_create do
    # 衝突しないか心配
    self.access_token = SecureRandom.hex(10)
  end
end

app/controllers/questionnaires_controller.rb
class QuestionnairesController < ApplicationController
  before_action :set_questionnaire, only: [:show, :edit, :update, :destroy, :answer, :create_answer, :index_answer, :admin]
  before_action :set_questionnaire_answers, only: [:index_answer]
  # GET /questionnaires
  # GET /questionnaires.json
  def index
    @questionnaires = Questionnaire.all
  end

  # GET /questionnaires/1
  # GET /questionnaires/1.json
  def show
  end

  # GET /questionnaires/1/admin
  def admin
    session[:q_password] = params[:q_password]
    redirect_to @questionnaire, alert: 'パスワードが違います' unless @questionnaire.authenticate(session[:q_password])
  end

  # GET /questionnaires/new
  def new
    @questionnaire = Questionnaire.new
    # ネスト先の子モデル questionnaire_items とその先の孫モデル questionnaire_choices_options をあらかじめ buildしておく
    # 作っておかないとフォームが表示されない
    @questionnaire.questionnaire_items.build{|item| item.questionnaire_choices_options.build}
  end

  # GET /questionnaires/1/edit
  def edit
  end

  # POST /questionnaires
  # POST /questionnaires.json
  def create
    # TODO きちんとネストされたフォームに合わせる
    @questionnaire = Questionnaire.new(questionnaire_params)
    # 本当は複数のitemおよびchoicesが飛んでくるからどう処理しようものか。。。
    questionnaire_item = QuestionnaireItem.new(questionnaire_item_params)
    questionnaire_choices_option = QuestionnaireChoicesOption.new(questionnaire_choices_option_params)
    questionnaire_choices_option.questionnaire_item = questionnaire_item
    questionnaire_item.questionnaire = @questionnaire

    respond_to do |format|
      # 個別に一つ一つ保存していくのではなく一気に保存したい
      if questionnaire_choices_option.save && questionnaire_item.save && @questionnaire.save
        format.html { redirect_to @questionnaire, notice: 'Questionnaire was successfully created.' }
        format.json { render :show, status: :created, location: @questionnaire }
      else
        format.html { render :new }
        format.json { render json: @questionnaire.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questionnaires/1
  # PATCH/PUT /questionnaires/1.json
  def update
    respond_to do |format|
      if @questionnaire.update(questionnaire_params)
        format.html { redirect_to @questionnaire, notice: 'Questionnaire was successfully updated.' }
        format.json { render :show, status: :ok, location: @questionnaire }
      else
        format.html { render :edit }
        format.json { render json: @questionnaire.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questionnaires/1
  # DELETE /questionnaires/1.json
  def destroy
    @questionnaire.destroy
    respond_to do |format|
      format.html { redirect_to questionnaires_url, notice: 'Questionnaire was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /questionnaires/1/answer
  def answer
    @questionnaire_answer = QuestionnaireAnswer.new
  end

  def create_answer
    # TODO 本当はここで永続化したくない
    @QuestionnaireAnswer = QuestionnaireAnswer.new(questionnaire: @questionnaire)

    new_qies = []
    questionnaire_item_answers_params.each_with_index do |qia_params, i|
      qia = QuestionnaireItemAnswer.new(qia_params)
      qia.questionnaire_choices_option_ids = params[:questionnaire_choices_options][i.to_s]
      qia.questionnaire_answer = @QuestionnaireAnswer
      new_qies << qia
    end
    @QuestionnaireAnswer.questionnaire_item_answers = new_qies
    
    respond_to do |format|
      # 個別に一つ一つ保存していくのではなく一気に保存したい
      if @QuestionnaireAnswer.save
        format.html { redirect_to @questionnaire, notice: '回答ありがとうございました。' }
      else
        format.html { render :new }
      end
    end
  end

  def index_answer
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_questionnaire
      @questionnaire = Questionnaire.friendly.find(params[:id])
    end

    def set_questionnaire_answer
      @questionnaire_answer = QuestionnaireAnswer.find(params[:id])
    end

    def set_questionnaire_answers
      # idで検索できないのはしかたないか？
      @questionnaire_answers = QuestionnaireAnswer.where(questionnaire: @questionnaire)
    end

    def set_questionnaire_item
      @questionnaire_item = QuestionnaireItem.find(params[:id])
    end

    def set_questionnaire_item_answers
      @questionnaire_item_answers = QuestionnaireItemAnswer.where(questionnaire_item: params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    # TODO きちんとネストされたフォームに合わせる(たぶん一つにまとまる)
    def questionnaire_params
      params[:questionnaire].try!(:permit!)
    end

    def questionnaire_item_params
      params[:questionnaire_item].try!(:permit!)
    end

    def questionnaire_choices_option_params
      params[:questionnaire_choices_option].try!(:permit!)
    end

    def questionnaire_item_answers_params
      params[:questionnaire_item_answers].each do |qia_params|
        qia_params.try!(:permit!)
      end
    end
end

app/helpers/questionnaires_helper.rb
module QuestionnairesHelper
end

app/views/questionnaires/_answer_form.html.erb
<%= form_for(questionnaire_answer, :url => {:action => :create_answer}) do |f| %>
  <% questionnaire.questionnaire_items.each_with_index do |item, index| %>
    <hr>
    <%= fields_for "questionnaire_item_answers[]", QuestionnaireItemAnswer.new do |i| %>
      <label><%= item.title %></label>
      <%= i.hidden_field 'questionnaire_item_id', value: item.id %>

      <div class="field">
      <% if item.is_multiple %>
        <%= collection_check_boxes(:questionnaire_choices_options, index, item.questionnaire_choices_options, :id, :option_name, include_hidden: false) %> 
      <% elsif %>
        <%= collection_radio_buttons(:questionnaire_choices_options, index, item.questionnaire_choices_options, :id, :option_name, include_hidden: false) %> 
      <% end %>
      </div>
      <% if item.is_exist_free_text %>
        <div class="field">
          <%= i.text_area :free_text_answer, class: 'form-control' %>
        </div>
      <% end %>
    

    <% end %>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questionnaires/_form.html.erb
<%= simple_form_for(questionnaire) do |f| %>
  <% if questionnaire.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(questionnaire.errors.count, "error") %> prohibited this questionnaire from being saved:</h2>

      <ul>
      <% questionnaire.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.input :title, label: 'アンケートタイトル', class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.input :password, label: '回答結果閲覧用パスワード', class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.input :header_discription, label: '説明(タイトルの下に表示されます)', class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.input :footer_discription, label: '説明(一番下に表示されます)', class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.input :published_from, label: '回答開始期間', class: 'form-control date-picker', use_month_numbers: true %>
  </div>

  <div class="field">
    <%= f.input :published_to, label: '回答終了期間', class: 'form-control date-picker', use_month_numbers: true %>
  </div>
  <%= f.simple_fields_for :questionnaire_items do |i| %>
    <%= render 'questionnaire_item_fields', f: i %>
  <% end %>
  <%= link_to_add_association 'item追加', f, :questionnaire_items %>

  <div class="actions">
    <%= f.submit 'アンケート作成' %>
  </div>
<% end %>

app/views/questionnaires/_questionnaire_choices_option_fields.html.erb
<div class="field">
  <%= f.input :option_name, label: '選択肢名', class: 'form-control' %>
</div>
<%= link_to_remove_association '選択肢削除', f, class: 'btn btn-default' %>

app/views/questionnaires/_questionnaire_item_fields.html.erb
<!--汎用で使いたいから application.js に書くべきだと思うんだけど、そこに書くとたまに動かなくなる　一旦ここに
でもこれはカスタマイズしたからここに個別でいい？？-->
<%= javascript_tag do %>
  $(function(){
    $(".select2").select2({
      tags: true,
      tokenSeparators: [',', ' '],
      // TODO そもそも出さないようにしたいが一旦メッセージを出さないように
      language: {"noResults": function(){ return;}}

    });
  });
<% end %>
<div class="field">
  <%= f.input :title, label: 'アンケートアイテムタイトル', class: 'form-control' %>
</div>
<div class="field">
  <%= f.input :sort_number, label: 'ソート順', class: 'form-control' %>
</div>
<div class="field">
  <%= f.input :is_exist_free_text, label: 'テキストエリア表示', class: 'form-control' %>
</div>
<div class="field">
  <%= f.input :is_multiple, label: '選択肢複数選択可', class: 'form-control' %>
</div>
<%= f.simple_fields_for :questionnaire_choices_options do |o| %>
  <%= render 'questionnaire_choices_option_fields', f: o %>
<% end %>
<div class="field">
  <%= f.association :questionnaire_choices_options,
    required: false,
    input_html: { class: 'select2' },
    collection: [],
    include_hidden: false
  %>
</div>
<%= link_to_add_association '選択肢追加', f, :questionnaire_choices_options, class: 'btn btn-default' %>

<%= link_to_remove_association 'item削除', f, class: 'btn btn-default' %>

app/views/questionnaires/admin.html.erb
<h2><%= @questionnaire.title %> 管理ページ</h2>

<%# TODO 各種操作パスワードを必要に %>
<p><%= button_to 'アンケートの回答一覧を見る', index_answer_questionnaire_path, method: :get %></p>
<p><%= button_to 'アンケートを削除する', @questionnaire, method: :delete, data: { confirm: 'Are you sure?' } %></p>

app/views/questionnaires/answer.html.erb
<h2><%= @questionnaire.title %></h2>
<%= simple_format(@questionnaire.header_discription) %>

<%= render 'answer_form', questionnaire: @questionnaire, questionnaire_answer: @questionnaire_answer %>
<%= simple_format(@questionnaire.footer_discription) %>

app/views/questionnaires/edit.html.erb
<h1>アンケート編集</h1>

<%= render 'form', questionnaire: @questionnaire %>

<%= link_to 'Show', @questionnaire %> |
<%= link_to 'Back', questionnaires_path %>

app/views/questionnaires/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Questionnaires</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questionnaires.each do |questionnaire| %>
      <tr>
        <td><%= link_to 'Show', questionnaire %></td>
        <td><%= link_to 'Edit', edit_questionnaire_path(questionnaire) %></td>
        <td><%= link_to 'Destroy', questionnaire, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Questionnaire', new_questionnaire_path %>

app/views/questionnaires/index_answer.html.erb
<h2><%= @questionnaire.title%>回答一覧</h2>

<% @questionnaire_answers.each do |qa| %>
  <p><%= link_to '回答確認', qa %></p>
<% end %>

app/views/questionnaires/new.html.erb
<h1>アンケート新規作成</h1>

<%= render 'form', questionnaire: @questionnaire %>

<%= link_to 'Back', questionnaires_path %>

app/views/questionnaires/show.html.erb
<%# TODO 二つ書くの冗長だからまとめられないかしら？ %>
<% if flash[:notice] %>
  <div class="notice alert-success">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
  </div>
<% end %>

<h2><%= @questionnaire.title %></h2>
<%= simple_format(@questionnaire.header_discription) %>
<% @questionnaire.questionnaire_items.each do |item| %>
  <hr>
  <h4><%= item.title %></h4>
  <p>選択肢：
  <% item.questionnaire_choices_options.each do |option| %>
    <%= option.option_name %>&nbsp;
  <% end %></p>
<% end %>
<%= simple_format(@questionnaire.footer_discription) %>

<%= link_to 'アンケートに答える', answer_questionnaire_path(@questionnaire) %>

<% #link_to 'Edit', edit_questionnaire_path(@questionnaire) TODO アンケート回答期間でないかつ、誰もアンケートに答えてない場合に出す%>
<%= form_tag admin_questionnaire_path(@questionnaire) do %>
  <div class="field">
    <%= label_tag 'アンケートパスワード'%>
    <%= password_field_tag 'q_password' %>
    <%= submit_tag  'アンケート管理画面へ' %>
  </div>
<% end %>

app/views/questionnaires/show_answer.html.erb
<h2>回答結果</h2>

<% @questionnaire_answer.questionnaire_item_answers.each do |qia| %>
  <hr>
  <h4><%= qia.questionnaire_item.title %></h4>
  <p>
    <% unless qia.questionnaire_choices_options.blank? %>
      選択肢:
      <% qia.questionnaire_choices_options.each do |option| %>
        <%= option.try(:option_name) %>&nbsp;
      <% end %>
    <% end %>
  </p>
  <%= simple_format(qia.free_text_answer) %>
  <p><%= link_to 'この解答欄の回答一覧を見る', show_answers_questionnaire_item_path(qia.questionnaire_item) %></p>
<% end %>

app/views/questionnaires/show_answers.html.erb
<h2><%= @questionnaire.title%>回答一覧</h2>

<% @questionnaire_answers.each do |qa| %>
  <p><%= link_to '回答確認', show_answer_questionnaire_path(qa) %></p>
<% end %>

app/views/questionnaires/show_answers_questionnaire_item.html.erb
<h4><%= @questionnaire_item.title %>の回答一覧</h4>

<% @questionnaire_item_answers.each do |qia| %>
  <hr>
  <p>
    <% unless qia.questionnaire_choices_options.blank? %>
      選択肢:
      <% qia.questionnaire_choices_options.each do |option| %>
        <%= option.try(:option_name) %>&nbsp;
      <% end %>
    <% end %>
  </p>
  自由回答欄:<%= simple_format(qia.free_text_answer) %>
  <p><%= link_to 'この回答者の他の回答も見る', show_answer_questionnaire_path(qia.questionnaire_answer) %></p>

<% end %>