config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  resources :types
  resources :teams, except:[:edit]
  post 'teams/:id/edit', to: 'teams#edit', as: 'edit_team'
  post 'teams/:id/admin', to: 'teams#admin', as: 'admin_team'
  resources :recruits, except:[:edit]
  post 'recruits/:id/edit', to: 'recruits#edit', as: 'edit_recruit'
  get 'about', to: 'about#index', as: 'about'
  resources :questionnaires
  get 'questionnaires/:id/answer', to: 'questionnaires#answer', as: 'answer_questionnaire'
  post 'questionnaires/:id/create_answer', to: 'questionnaires#create_answer', as: 'create_answer_questionnaire'
  get 'questionnaires/:id/index_answer', to: 'questionnaires#index_answer', as: 'index_answer_questionnaire'
  post 'questionnaires/:id/admin', to: 'questionnaires#admin', as: 'admin_questionnaire'
  get 'questionnaire_answers/:id', to: 'questionnaire_answers#show', as: 'questionnaire_answer'
  get 'questionnaire_items/:id', to: 'questionnaire_items#show', as: 'questionnaire_item'

end

app/models/recruit.rb
# == Schema Information
#
# Table name: recruits
#
#  id             :integer          not null, primary key
#  title          :string           not null
#  practice_place :string
#  practice_time  :string
#  free_text      :text
#  published_from :datetime         not null
#  published_to   :datetime         not null
#  team_id        :integer          not null
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Recruit < ApplicationRecord
  belongs_to :team

  has_many :recruit_instruments
  has_many :instruments, :through => :recruit_instruments

  scope :has_instrument_id, -> instrument_id {
    joins(:instruments).where('instruments.id = ?', instrument_id)
  }

  scope :has_type_id, -> type_id {
    joins(team: :types).where('types.id = ?', type_id)
  }
  # もっとスマートにかける？
  scope :is_published, -> {
    now = DateTime.now
    where("published_from <= ?", now).where("published_to >= ?", now)
  }

  # TODO 誰かどうにかして。。。　あと複数キーワード対応も
  scope :search_freeword, -> word {
    w = "%#{word}%"
    joins(:team).where("(recruits.title LIKE ?) or (recruits.free_text LIKE ?) or (recruits.practice_place LIKE ?) or (recruits.practice_time LIKE ?) or (teams.name LIKE ?)", w, w, w, w, w)
  }
end

app/models/team.rb
# == Schema Information
#
# Table name: teams
#
#  id              :integer          not null, primary key
#  name            :string           not null
#  password_digest :string           not null
#  mail            :string
#  url             :string
#  free_text       :text
#  is_public       :boolean          default("false")
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Team < ApplicationRecord
  # SecurePassword有効
  has_secure_password

  has_many :recruits
  has_many :team_types
  has_many :types, :through => :team_types
  has_many :team_regions
  has_many :regions, :through => :team_regions

  scope :is_public, -> {
    where(is_public: true)
  }
end

app/controllers/recruits_controller.rb
class RecruitsController < ApplicationController
  before_action :set_recruit, only: [:show, :edit, :update, :destroy]
  before_action :set_team, only: [:new, :edit]
  before_action :reset_password_session, only: [:show, :index]

  # GET /recruits
  # GET /recruits.json
  def index
    query = Recruit.is_published
    query = query.has_type_id(params[:type_id]) if params[:type_id].present?
    query = query.has_instrument_id(params[:instrument_id]) if params[:instrument_id].present?
    query = query.search_freeword(params[:freeword]) if params[:freeword].present?

    @recruits = query.page(params[:page])
  end

  # GET /recruits/1
  # GET /recruits/1.json
  def show
  end

  # GET /recruits/new
  def new
    @team ? team = @team : team = Team.new
    @recruit = Recruit.new(team: team, published_from: DateTime.now, published_to: DateTime.now)
  end

  # POST /recruits/1/edit
  def edit
    session[:password] = params[:password]
    redirect_to @recruit, alert: 'パスワードが違います' unless @recruit.team.authenticate(session[:password])
  end

  # POST /recruits
  # POST /recruits.json
  def create
    @recruit = Recruit.new(recruit_params)
    @recruit.team = Team.new(team_params) unless @recruit.team

    respond_to do |format|
      if @recruit.save
        format.html { redirect_to @recruit, notice: 'Recruit was successfully created.' }
        format.json { render :show, status: :created, location: @recruit }
      else
        format.html { render :new }
        format.json { render json: @recruit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recruits/1
  # PATCH/PUT /recruits/1.json
  def update
    respond_to do |format|
      if @recruit.update(recruit_params)
        format.html { redirect_to @recruit, notice: 'Recruit was successfully updated.' }
        format.json { render :show, status: :ok, location: @recruit }
      else
        format.html { render :edit }
        format.json { render json: @recruit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recruits/1
  # DELETE /recruits/1.json
  def destroy
    return redirect_to @recruit, alert: 'パスワードが違います' unless @recruit.team.authenticate(session[:password])
    @recruit.destroy
    respond_to do |format|
      format.html { redirect_to recruits_url, notice: 'Recruit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recruit
      @recruit = Recruit.find(params[:id])
    end

    def set_team
      params[:team_id] ? @team = Team.find(params[:team_id]) : @recruit ? @team = @recruit.team : Team.new
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recruit_params
      # TODO view からくる params が微妙な入れ子になってて要修正？
      # <ActionController::Parameters {"team"=>{"name"=>"ddd", "password"=>"ppp"}, "practice_place"=>"aaa", "practoce_time"=>"ttt", "free_text"=>"fff"} permitted: false>
      params[:recruit].try!(:permit!)
    end

    def team_params
      params[:team].try!(:permit!)
    end

    def reset_password_session
      session[:password] = nil if session[:password]
    end
end

app/helpers/recruits_helper.rb
module RecruitsHelper
end

app/views/recruits/_form.html.erb
<!--汎用で使いたいから application.js に書くべきだと思うんだけど、そこに書くとたまに動かなくなる　一旦ここに-->
<%= javascript_tag do %>
  $(function(){
    $(".select2").select2({
    });
  });
<% end %>

<%= form_for(recruit) do |f| %>
  <% if recruit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recruit.errors.count, "error") %> prohibited this recruit from being saved:</h2>

      <ul>
      <% recruit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :team_id , class: 'form-control'%>

  <div class="field">
    <%= f.label :'募集タイトル' %>
    <%= f.text_field :title , class: 'form-control'%>
  </div>
  <% unless @team %>
    <%= fields_for recruit.team do |t| %>
      <div class="field">
        <%= t.label :'団体名' %>
        <%= t.text_field :name, class: 'form-control' %>
      </div>
      <div class="field">
        <%= t.label :'password' %>
        <%= t.password_field :password, class: 'form-control' %>
      </div>
      <div class="field">
        <%= t.label :'団体種別' %><br/>
        <%= t.select :type_ids, Type.all.map {|t| [t.name, t.id]}, {}, multiple: true, class: 'form-control select2' %>
      </div>
      <div class="field">
        <%= t.label :'活動地域' %><br/>
        <%= t.select :region_ids, Region.all.map {|r| [r.name, r.id]}, {}, multiple: true, class: 'form-control select2' %>
      </div>
      <div class="field">
        <%= t.label :'連絡用メールアドレス' %>
        <%= t.text_field :mail, class: 'form-control' %>
      </div>
      <div class="field">
        <%= t.label :'団体ホームメージ' %>
        <%= t.text_field :url, class: 'form-control' %>
      </div>
    <% end %>
  <% end %>
  <div class="field">
    <%= f.label :'練習場所' %>
    <%= f.text_field :practice_place , class: 'form-control'%>
  </div>

  <div class="field">
    <%= f.label :'練習時間' %>
    <%= f.text_field :practice_time, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :'募集楽器' %><br/>
    <%= f.select :instrument_ids, Instrument.all.map {|i| [i.to_name_and_short_name, i.id]}, {}, multiple: true, class: 'form-control select2' %>
  </div>

  <div class="field">
    <%= f.label :'自由欄'%>
    <%= f.text_area :free_text, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :'掲載開始期間'%>
    <%= f.datetime_select :published_from, class: 'form-control date-picker', :use_month_numbers => true %>
  </div>

  <div class="field">
    <%= f.label :'掲載終了期間'%>
    <%= f.datetime_select :published_to, class: 'form-control date-picker', :use_month_numbers => true %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recruits/_recruit.html.erb
<div class="col-md-12">
  <div class="panel panel-info">
    <div class="panel-heading">
      <h3 class="panel-title"><%= recruit.title %></h3>
    </div>
    <div class="panel-body">
      <p>
        <% recruit.team.types.each do |type| %>
          <span class="label label-info"><%= type %></span>
        <% end %>
      </p>
      <h5><%= recruit.team.name %></h5>
      <p>練習場所:<%= recruit.practice_place %></p>
      <p>練習時間:<%= recruit.practice_time %></p>
      <p>募集楽器:<br>
        <% recruit.instruments.map { |instrument| instrument.instrument_category }.uniq.each do |c| %>
          &nbsp;&nbsp;<%= c %>:
          <% recruit.instruments.each do |i| %>
            <span class="badge"><%= i.short_name if i.instrument_category == c %></span>
          <% end %><br>
        <% end %>
      </p>
    </div>
  </div>
</div>

app/views/recruits/edit.html.erb
<div class="container">
  <div class="row">
    <h1>団員募集編集</h1>
    <p><%= link_to '団体を編集する', edit_team_path(@team), method: :post %></p>

    <%= render 'form', recruit: @recruit%>


    <p><%= button_to '募集を削除する', @recruit, method: :delete, data: { confirm: '本当に削除しますか?' }  %></p>
    <%= link_to '団員募集に戻る', recruits_path %>
  </div>
</div>

app/views/recruits/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1>団員募集</h1>
        <div class="row">
          <%= form_tag({controller: "recruits"}, method: :get)do %>
            <div class="col-md-9">
              <h3>団員募集検索</h3>
              <div class="form-group">
                <label class="col-sm-4" for="service_vlan_resource_id">団体種別</label>
                <div class="col-sm-8">
                  <%=
                    select_tag 'type_id',
                                options_from_collection_for_select(Type.all, :id, :to_s, params[:type_id]),
                                class: 'form-control chosen-select',
                                include_blank: true
                  %>
                </div>
                <label class="col-sm-4" for="service_vlan_resource_id">募集楽器</label>
                <div class="col-sm-8">
                  <%=
                    select_tag 'instrument_id',
                                options_from_collection_for_select(Instrument.all, :id, :to_name_and_short_name, params[:instrument_id]),
                                class: 'form-control chosen-select',
                                include_blank: true
                  %>
                </div>
                <label class="col-sm-4" for="service_vlan_resource_id">フリーワード検索</label>
                <div class="col-sm-8">
                  <!--TODO rails のヘルパー使うようにしたい、もちろん複数キーワードに対応も-->
                  <%= text_field_tag :freeword, '', class: 'form-control', placeholder: "複数キーワードには対応してません" %>
                </div>
              </div>
            </div>
            <div class="col-sm-offset-1 col-md-2"><br><br><br><br><%= submit_tag  '検索', class: "btn btn-default btn-lg" %></div>
          <% end %>
            <div class="row">
              <div class="col-md-12">
                <% @recruits.each do |recruit| %>
                  <%= link_to recruit, style: "text-decoration:none;" do %>
                    <%= render partial: 'recruit', locals: { recruit: recruit } %>
                  <% end %>
                <% end %>
                <%= paginate @recruits %>
                <br>

                <%= link_to '新しく団員募集をする', new_recruit_path %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/recruits/new.html.erb
<div class="container">
  <div class="row">
  <h1>団員募集新規作成</h1>

  <%= render 'form', recruit: @recruit %>

  <%= link_to '団員募集に戻る', recruits_path %>
  </div>
</div>

app/views/recruits/show.html.erb
<% if flash[:alert] %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
  </div>
<% end %>
<div class="container">
  <div class="row">
    <% if @recruit.published_from > DateTime.now %>
      <div class="alert alert-danger">
        この募集は掲載期間前です
      </div>
    <% else %>
      <% if @recruit.published_to < DateTime.now %>
        <div class="alert alert-danger">
          この募集は募集期間を過ぎています
        </div>
      <% end %>
      <h1><%= @recruit.team.name %></h1>
      <% @recruit.team.types.each do |type| %>
        <span class="badge"><%= type %></span>
      <% end %>
      <div class="row">
        <div class="col-sm-offset-1 col-md-11">
          <p>練習場所:<%= @recruit.practice_place %></p>
          <p>練習時間:<%= @recruit.practice_time %></p>
          <p>連絡先:<%= @recruit.team.mail %></p>
          <p>URL:<%= link_to @recruit.team.url %></p>
          <p>募集楽器:<br>
            <% @recruit.instruments.map { |instrument| instrument.instrument_category }.uniq.each do |c| %>
              &nbsp;&nbsp;<%= c %>:
              <% @recruit.instruments.each do |i| %>
                <span class="badge"><%= i if i.instrument_category == c %></span>
              <% end %><br>
            <% end %>
          </p>
          <%= simple_format(@recruit.free_text) %>
        </div>
      </div>
    <% end %>
    <%= form_tag edit_recruit_path(@recruit) do %>
      <div class="field">
        <%= label_tag 'パスワード'%>
        <%= password_field_tag 'password' %>
        <%= submit_tag  '編集' %>
      </div>
    <% end %>
    <p><%= link_to '団員募集に戻る', recruits_path %></p>
  </div>
</div>