config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  resources :types
  resources :teams, except:[:edit]
  post 'teams/:id/edit', to: 'teams#edit', as: 'edit_team'
  post 'teams/:id/admin', to: 'teams#admin', as: 'admin_team'
  resources :recruits, except:[:edit]
  post 'recruits/:id/edit', to: 'recruits#edit', as: 'edit_recruit'
  get 'about', to: 'about#index', as: 'about'
  resources :questionnaires
  get 'questionnaires/:id/answer', to: 'questionnaires#answer', as: 'answer_questionnaire'
  post 'questionnaires/:id/create_answer', to: 'questionnaires#create_answer', as: 'create_answer_questionnaire'
  get 'questionnaires/:id/index_answer', to: 'questionnaires#index_answer', as: 'index_answer_questionnaire'
  post 'questionnaires/:id/admin', to: 'questionnaires#admin', as: 'admin_questionnaire'
  get 'questionnaire_answers/:id', to: 'questionnaire_answers#show', as: 'questionnaire_answer'
  get 'questionnaire_items/:id', to: 'questionnaire_items#show', as: 'questionnaire_item'

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">　<!-- I want to fix this navigation bar on the top of the site. -->
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">Schubert</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
   <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><a href="<%= recruits_path %>">団員募集</a></li>
        <li><a href="<%= teams_path %>">団体一覧</a></li>
        <li><a href="<%= recruits_path %>">演奏会情報</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="<%= about_path %>">About</a></li>
      </ul>
  </div><!-- /.container-->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Schubert</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body>
    <%= render "layouts/header" %>

    <%= yield %>
  </body>
</html>